































// Similarly update other category-related functions}  return { categories, loading, error };  };    }      setLoading(false);    } finally {      setError(error.message);    } catch (error) {      setCategories(data);      if (error) throw error;              .order('name');        .select('*')        .from('categories')      const { data, error } = await supabase    try {  const fetchCategories = async () => {  }, []);    fetchCategories();  useEffect(() => {  const [error, setError] = useState(null);  const [loading, setLoading] = useState(true);  const [categories, setCategories] = useState([]);export function useCategories() {import { supabase } from '../utils/supabaseClient';import { useState, useEffect } from 'react';