// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mylldnnmdqhzsrmibmio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bGxkbm5tZHFoenNybWlibWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzkwNjgsImV4cCI6MjA1NTU1NTA2OH0.SRbtgWbcAMXMkLinxnumc-aOZfZH6TDcJPc4e0c6eKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);